### ISSUE TITLE
Airline/Lightline compatibility

### ISSUE THREAD

**Issue by jordihm9** [ray-x/aurora#10]
Hi!
Love this scheme, I've been trying quite a lot and I'm definetly gonna use this one!

It just have a downside, it doesn't have `lightline` or `airline` compatibility, it is possible to add it?

Many thanks & congrats!

**Comment by ray-x** [comment]
@jordihm9 
Would you check the latest version works for you?

**Comment by jordihm9** [comment]
Yes! how can I update? I'm using _Plug_ as my package manager

**Comment by ray-x** [comment]
The changes were pushed to github, Please try:
`PlugUpdate `
or `PlugUpdate aurora`

**Comment by jordihm9** [comment]
Nice! Thanks a lot! 💯
