### ISSUE TITLE
fix new treesitter broken syntax hightlighting

### ISSUE THREAD

**Issue by dobbbri** [ray-x/aurora#11]
fix new treesitter broken syntax hightlighting

**Comment by ray-x** [comment]
Could you be more specific? which TS parser are you using and what error you saw?

**Comment by dobbbri** [comment]
see this https://github.com/nvim-treesitter/nvim-treesitter/commit/42ab95d5e11f247c6f0c8f5181b02e816caa4a4f

**Comment by ray-x** [comment]
pushed a fix
