### ISSUE TITLE
YAML syntax highlighting

### ISSUE THREAD

**Issue by liketoeatcheese** [ray-x/aurora#13]
Hi guys,

Firstly, love the work! the colorscheme is just wonderful. 

To my question, I want to tweak the color of the YAML file, to be specific: the key inside the file, instead of white, I want a different color. How would I change that?

I'm using Packer btw.

I tried to go to .local/share/nvim/site/pack/packer/start/aurora/estilos/syntax/yaml.yml, tweaked all values, :PackerSync, :colorscheme aurora. The whole lot, but the file still stays the same. Am I missing anything. Would appreciate any guidance :)

**Comment by ray-x** [comment]
1> Are you using neovim 0.7.x +
2> Are you using treesitter for yml?
The yaml only used for vim users. 

Suppose you are using both.
Then you may need to adjust the treesitter setup for 
@string   @field

So in you setup with lua 

```lua
if vim.o.ft == 'yaml' then
  vim.api.nvim_set_hl(0, '@string', {fg='#59E343'})
  vim.api.nvim_set_hl(0, '@field', {fg='#f93393'})
end

```

**Comment by ray-x** [comment]
Did you install yaml parser?
`TSInstall yaml`

**Comment by liketoeatcheese** [comment]
Hi Ray,

Yes, it is installed. I use mason and also added it to my lspconfig like so:
```
require("lspconfig").yamlls.setup({
  on_attach = require("wpham.lsp.handlers").on_attach,
  capabilities = require("wpham.lsp.handlers").capabilities,
  settings = {
    yaml = {
      --[[ format = { ]]
      --[[   enable = true ]]
      --[[ }, ]]
      schemas = {
        --[[ ["https://raw.githubusercontent.com/quantumblacklabs/kedro/develop/static/jsonschema/kedro-catalog-0.17.json"] = "conf/**/*catalog*", ]]
        --[[ ["https://json.schemastore.org/github-workflow.json"] = "/.github/workflows/*", ]]
        kubernetes = "/*.yaml",
      },
    },
  },
})
```

The language server is there. I also tried `TSInstall yaml` like you suggested, and it also said yaml is already installed. I reinstalled it but nothing've changed.
![image](https://user-images.githubusercontent.com/88610355/207734211-7504a38f-ee85-49b5-ac98-1a87c53eee65.png)

**Comment by ray-x** [comment]
How about you run 
`vim.api.nvim_set_hl(0, '@string', {fg='#59E343'})`
after yml file loaded?

**Comment by liketoeatcheese** [comment]
I got this error: `E194: No alternate file name to substitue for '#'`
![image](https://user-images.githubusercontent.com/88610355/207735203-f0d25139-a6f6-4bce-9ada-8c1284fba1e8.png)

![image](https://user-images.githubusercontent.com/88610355/207735269-281523eb-45c2-474d-a5b2-8495b01b7568.png)

**Comment by ray-x** [comment]
should be like this:
`:lua vim.api.nvim_set_hl(0, '@string', {fg='#59E343'})`

**Comment by liketoeatcheese** [comment]
That works

**Comment by ray-x** [comment]
It is very likely when you run nvim_set_hl the vim.o.ft was not detected.
You can do that in yamlls on_attach(), or more recommended
in `after/ftplugin/yaml.vim`


```lua

lua <<EOF
  vim.api.nvim_set_hl(0, '@string', {fg='#59E343'})
  vim.api.nvim_set_hl(0, '@field', {fg='#f93393'})
  vim.api.nvim_set_hl(0, '@number', {fg='#e933e3'})
EOF
```

**Comment by liketoeatcheese** [comment]
Worked perfectly!!!! Thanks for your assist Ray

**Comment by liketoeatcheese** [comment]
Oh btw, I have been curios about this, what's this sidebar package name? Or is this a custom thing.
![image](https://user-images.githubusercontent.com/88610355/207743870-6b5d5a9d-6795-45de-b9a7-359ad851417c.png)
