### ISSUE TITLE
Failed to run ''config" for aurora

### ISSUE THREAD

**Issue by zhangmichael2k6** [ray-x/aurora#16]
Hello friend, i have encounter this problem while installing your aurora colorscheme into my nvim config via lazy.nvim
The error is look like this 
![Screenshot from 2024-07-07 21-58-51](https://github.com/ray-x/aurora/assets/111274932/f1a7c1e7-e75a-4dc0-aa6e-019129f34cf0)
What is the problem here ????

**Comment by ray-x** [comment]
Could you post your config for aurora? Thanks!

**Comment by zhangmichael2k6** [comment]
nvm, i already figured it out :))))
