### ISSUE TITLE
How to config aurora using lazy.nvim style ???

### ISSUE THREAD

**Issue by zhangmichael2k6** [ray-x/aurora#17]
Hello, it's me again </br>
I have install the colorscheme sucessfully, but idk how to config the thing in lazy.nvim style ??? </br>
This is my code 
![ArcoLinux-2024-07-16-1721146547_screenshot_1366x768](https://github.com/user-attachments/assets/a9b260f7-55f6-48a1-b0d5-0437b36955d5)
How do I config this 
Thanks !

**Comment by ray-x** [comment]
Your config looks fine to me. Mine config look like this: 

```lua
{
    'ray-x/aurora',
    init = function()
      vim.g.aurora_italic = 1
      vim.g.aurora_transparent = 1
      vim.g.aurora_bold = 1
    end,
    config = function()
        vim.cmd.colorscheme "aurora"
    end,
  }
```

**Comment by zhangmichael2k6** [comment]
ok, thanks man, i figured it out
