### ISSUE TITLE
[Color Issue] Am I missing something?

### ISSUE THREAD

**Issue by hamza02x** [ray-x/aurora#3]
Please take a look at my screenshot. I am missing something most probably.

`wrong syntax highlighting`?

![image](https://user-images.githubusercontent.com/48919542/128112759-285cd222-f934-4ef1-8c0f-b8994bafa3fa.png)

`local.vim` config file:

![image](https://user-images.githubusercontent.com/48919542/128112862-e11fb950-17a4-40ce-bc6e-83320e820807.png)

`local.plugins.vim` config file:

![image](https://user-images.githubusercontent.com/48919542/128113119-b9fed6b9-04b6-4d1f-8a8e-64203705c561.png)

Using this btw - https://github.com/rafi/vim-config

**Comment by ray-x** [comment]
If you are using go with a neovim. I recommend you add treesitter plugin. That will give you a better highlight.
If you are using vim/gvim. You may need install vim-go or govim plugin. That will give you a better highlight.

**Comment by hamza02x** [comment]
Thank you, just had to enable treesitter in configuration

![image](https://user-images.githubusercontent.com/48919542/128122702-f84de860-51fe-4d9c-9fe3-e43f9f4fd389.png)

![image](https://user-images.githubusercontent.com/48919542/128122720-72b476d8-63ae-4187-90bd-b37a193b3a7b.png)
