### ISSUE TITLE
Could you add a transparent background option like this: let g:aurora_transparent = 'true' 

### ISSUE THREAD

**Issue by forbearing** [ray-x/aurora#6]

**Comment by ray-x** [comment]
Default terminal looks good to me
<img width="796" alt="image" src="https://user-images.githubusercontent.com/1681295/177280045-3620c7ee-367e-41e4-87f7-204e7be21932.png">
Using kitty...

**Comment by peleusj** [comment]
Which kitty theme can make it transparent?

**Comment by ray-x** [comment]
I think it comes with Kitty setup, not the color scheme

**Comment by peleusj** [comment]
But the default setup seems can not make this theme transparent? 

The `background_opacity` setup also will not effect the nvim theme transparency.

The author of Kitty mentioned here: https://github.com/dracula/vim/issues/284#issuecomment-1086532742: 

> In kitty the background color is made transparent if it is the same as the terminals background color. In alacritty, the background color is made transparent only if there is no background color set. In typical vim color themes, the normal background is set explicitly to a color instead of remaining unset (which is bad for performance, but that's another issue). So since the normal background is set, alacritty wont make it transparent, but kitty will, assuming the color is the same as the terminal's background color.

So how do you achieve the result of your screenshot is interesting.

**Comment by ray-x** [comment]
Ok, I was wrong.
I have this in my setup
```
  vim.cmd("hi Normal guibg=NONE ctermbg=NONE") -- remove background
  vim.cmd("hi EndOfBuffer guibg=NONE ctermbg=NONE") -- remove background
```
Those will remove background. It was not kitty

**Comment by ray-x** [comment]
@peleusj Would you check if latest version works for you?

**Comment by peleusj** [comment]
Sorry for the delay.
It works perfect.
Thanks for your work!

**Comment by peleusj** [comment]
And I hava a little problem.
Each cmp compeltion item's document is not transparent when colorscheme's transparent is on.
Not sure if it is setttings of colorscheme or cmp itself.

**Comment by ray-x** [comment]
![image](https://user-images.githubusercontent.com/1681295/188346407-4246285e-48e9-4019-b69d-e52b86bab61f.png)
Not 100% sure, because my cmp popup is transparent.

**Comment by peleusj** [comment]
Yes, I test again, it is transparent. May be it is the background color too black and I did not discover it.
<img width="1317" alt="Screen Shot 2022-09-05 at 10 14 47" src="https://user-images.githubusercontent.com/17824110/188348209-5246e301-a15b-4d00-bf73-637d12ab8ae1.png">
