### ISSUE TITLE
Report error message when launched

### ISSUE THREAD

**Issue by tan-wei** [ray-x/aurora#8]
It will report:
```
Error detected while processing ColorScheme Autocommands for "*":
E121: Undefined variable: g:colors_name
E116: Invalid arguments for function CocHelperCallFn_m1_v0_13_0
```

**Comment by ray-x** [comment]
on top of the colorscheme vim file, `g:colors_name` is defined.
no idea how it was cleared in your case. Could you share a minium vimrc/init.lua I can reproduce.

```vim
" Colorscheme: " License: MIT""

if exists('g:colors_name')
    highlight clear
    if exists('syntax_on')
        syntax reset
    endif
endif
let g:colors_name="aurora"
```

**Comment by tan-wei** [comment]
I just use `Plug` to install `aurora`, and then I manually set the color scheme with `:colorscheme aurora`. Is it related to `coc`?

**Comment by tan-wei** [comment]
A complete configure file is [here](https://github.com/tan-wei/neovim-init.vim), I use a random choice plugin to choose color scheme. But if I manually change the color scheme with `:colorscheme aurora`, the error is the same.

**Comment by ray-x** [comment]
I noticed there is a commit I did not pushed. Could you update and try it again.

**Comment by tan-wei** [comment]
Seems OK now. The issue should be closed. Thanks very much.
