### ISSUE TITLE
italic  not working anymore

### ISSUE THREAD

**Issue by charlie39** [ray-x/aurora#9]
When i first installed , i used to get  italicised comment. But then suddenly italic stopped working. I am not sure whether it is clashing with other plugins or not but my aurora configs are placed at the bottom of init.lua, after all the configurations of other plugins.

Interesting to note that  i have tried other plugins like onedark and tokyodark and in both italic  is working.
This is the bottom section of my ```init.lua```  where i put the  colorscheme  configurations. 

```
------------------ Colorschemes -----------------------------

vim.cmd [[set bg=dark]]

--onedark
--[[ cmd 'packadd onedark.nvim'
local od = require('onedark')
od.setup {
  -- style = 'dark'
  style = 'darker',
  -- style = 'cool'
  -- style = 'deep'
  -- style = 'warm'
  -- style = 'warmer'
  transparent = true,
}
od.load() ]]

--tokyodark
--[[ cmd 'packadd tokyodark.nvim'
cmd 'colorscheme tokyodark' ]]

--aurora
-- aurora doesn't allow scope highlight from ts-refactor
cmd 'packadd aurora'
vim.g.aurora_italic = 1
cmd 'colorscheme aurora'

-- cmd 'colorscheme base16-atelier-savanna'
-- cmd 'colorscheme base16-atelier-plateau'
-- cmd 'colorscheme base16-3024'
-- cmd 'colorscheme base16-woodland'


-- ts-rainbow should be loaded after colorscheme
cmd 'packadd nvim-ts-rainbow'
-- cmd 'if &diff then highlight! link DiffText MatchParent end'

```

screenshot - > https://imgur.com/a/GnCn9Ew

**Comment by ray-x** [comment]
seems lua code doesn't respect the italic set. It is a bug I introduced.

**Comment by charlie39** [comment]
Does it involve refactoring the plugin or just the awk script?

**Comment by ray-x** [comment]
Pushed a fix. Could you have a look?

**Comment by charlie39** [comment]
> Pushed a fix. Could you have a look?
Yeah it's fixed
